spring:
  profiles:
    active: dev
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: abc@email.com
#    password: password
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#logging:
#  level:
#    com:
#      niladri:
#        Journalapp: DEBUG
weather:
  api:
    key: ae73ebc761923d0fc90df596e1ad7666